print('Welcome To trival facts')
name=input('what is your Name: ')
years=int(input("Your age in years :"))
weight=int(input('your weight in kgs : '))
print('So its been',years,'years you are in to this world',"\n")
print('weight on moon ',weight/6,"\n")
print('your weight on Sun will be',weight*27,"\n")
print ('your age in days: ',years*365 ,'\n','your age in hours: ',years*365*24,'\n','your age in minutes: ',years*365*24*60,'\n','your age in seconds: ',years*365*24*60*60)   
input ()
