
quote =("Life "+"is "+"really "+"simple, "+"but "+"we "+"insist "+"on "+"making "+"it "+"complicated."  )
print ("The sentence is- concatenation","\n")
print (quote,"\n")
print (" UpperCase ","\n")
print (quote.upper(),"\n")
print (" LowerCase","\n")
print (quote.lower(),"\n")
print ("Title comand","\n")
print (quote.title(),"\n")
print (" The sentence using replace comand-","\n")
print (quote.replace("complicated","hard"),"\n")
print ("using strip","\n")
print (quote.strip(),"\n")
print ("using swapCase","\n")
print (quote.swapcase(),"\n")
print ("using capitalize comand:","\n")
print (quote.capitalize(),"\n")
input('\npress enter to exit.\n')


